apiVersion: v1
kind: Service
metadata:
  name: {{ include "qdrant.headless.fullname" . }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.headless.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.headless.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.headless.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.headless.service.ports.p2p }}
      targetPort: tcp-p2p
      protocol: TCP
      name: tcp-p2p
  publishNotReadyAddresses: true
  selector:
    {{- include "qdrant.selectorLabels" . | nindent 4 }}
