apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.serviceAccount.namespaced }}
kind: RoleBinding
{{ else }}
kind: ClusterRoleBinding
{{ end -}}
metadata:
  name: {{ include "kubeview.fullname" . }}
  labels:
    {{- include "kubeview.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.serviceAccount.namespaced }}
  kind: Role
  {{ else }}
  kind: ClusterRole
  {{ end -}}
  name: {{ include "kubeview.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeview.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
