apiVersion: v2
appVersion: 2.1.1
description: Add-on for Kubernetes that makes it easy to write and deploy custom controllers
home: https://metacontroller.github.io/metacontroller/
kubeVersion: ">=1.16"
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: metacontroller
sources:
  - https://github.com/metacontroller/metacontroller
  - https://github.com/cowboysysop/charts/tree/master/charts/metacontroller
version: 1.1.2
dependencies:
  - name: common
    version: 1.7.1
    repository: https://charts.bitnami.com/bitnami/
