name: Renovate

on:
  schedule:
    - cron: '0 * * * 0'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Renovate
        uses: renovatebot/github-action@v40.3.1
        with:
          renovate-version: 38.119.0 # renovate: ghcr.io/renovatebot/renovate
        env:
          RENOVATE_CONFIG_FILE: renovate.json
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
